config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'webpages', to: 'webpages#index'
  resources :sessions, only: [:new,:create,:destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :blogs do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users,through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user

  def created_by?(input_user)
    return false unless input_user
    user_id == input_user.id
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_many :blogs

  validates :name,presence:true,length:{ maximum:40 }
  validates :email,presence:true,length:{ maximum:300 },
                  format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness:true

  before_save{ email.downcase! }
  has_secure_password
  validates :password,presence:true,length:{ minimum:6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
  end

  def authenticate
    return if logged_in?
    redirect_to root_path alert:"ログインしてください"
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :set_blog,only:[:show,:edit,:update,:destroy]

  def index
    @blogs = Blog.all.all.order("blogs.created_at desc")
  end

  def new
    @blog = Blog.new
  end

  def show
    if logged_in?
      @favorite = current_user.favorites.find_by(blog_id: @blog.id)
      @comment = @blog.comments.build
      @comments = @blog.comments
    else
      redirect_to blogs_path, notice: "ログインしてください"
    end

  end

  def create
    if logged_in?
      @blog = Blog.new(blog_params)
      @blog.user_id = current_user.id
      if @blog.save
        # BlogCreateMailer.blog_create_mail(current_user).deliver
        redirect_to blogs_path, notice:"作成しました"
      end
    else
        @blog = Blog.new(blog_params)
        redirect_to blogs_path, notice:"ログインしてください"
    end
  end

  def edit
  end

  def update
  if @blog.update(blog_params)
    redirect_to blogs_path, notice:"編集しました"
  else
    @blog = Blog.new(blog_params)
    render 'edit'
  end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path notice:"削除しました"
  end

  private
  def blog_params
    params.require(:blog).permit(:name,:title,:content)
  end

  def set_blog
   @blog = Blog.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)

  respond_to do |format|
    if @comment.save
        format.js { render :index }
    else
        format.html { redirect_to blog_path(@blog), notice: '投稿できませんでした' }
    end
   end
  end

  private

  def comment_params
    params.require(:comment).permit(:blog_id,:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate

  def create
    favorite = current_user.favorites.create(blog_id:params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(blog_id:params[:blog_id]).destroy
    redirect_to blogs_url,notice:"#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    logout
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
   if @user.save
    login(@user)
    redirect_to user_path(@user.id)
   else
    render 'new'
   end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
    @blog = current_user.favorites.find_by(blog_id:params[:blog_id])
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/blogs/edit.html.erb
<h2>編集する</h2>

<%= form_with(model:@blog) do |form|%>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="form-group">
        <div class="blog_title">
          <%=form.label :タイトル %>
          <%=form.text_field :title,class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="blog_content">
          <%=form.label :内容 %>
          <%=form.text_field :content,class:"form-control content_form"%>
        </div>
      </div>
        <%=form.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<div class="container">
  <div id="new-blog-link">
     <%= link_to '新規ブログを作成する', new_blog_path, class:"btn btn-primary btn-block" %>
  </div>
  <div class="row">
   <div class="col-md-12 col-sm-6">
    <% @blogs.each do |blog|%>
      <div class = "col-xs-12 col-md-6 blog-panel panel panel-default">
        <div class="panel-heading"><%= blog.id %>.<%= blog.title %></div>
        <div class="panel-body">
            <p><%= blog.content %></p>
            <p><%= blog.created_at %></p>
          <div class="blog-links">
              <%= link_to '詳細を表示する',blog_path(blog.id) ,class:"btn btn-success"%>
          <% if blog.created_by?(current_user) %>
              <%= link_to '編集する',edit_blog_path(blog.id),class:"btn btn-info" %>
              <%= link_to '削除する',blog_path(blog.id),method: :delete ,class:"btn btn-danger",data:{confirm:'本当に削除していいですか？'} %>
          <% end %>
          </div>
      </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= form_with(model:@blog) do |form|%>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="form-group">
        <div class="blog_title">
        <%=form.label :タイトル %>
        <%=form.text_field :title,class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="blog_content">
        <%=form.label :内容 %>
        <%=form.text_field :content,class: "form-control content_form"%>
        </div>
      </div>
        <%=form.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/blogs/show.html.erb
<h2>ブログ詳細</h2>

 <div class= "blog_show">
    <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <div class="row">
        <div class="col-md-12 col-sm-6 blog-panel panel panel-default">
          <div class="panel-heading"><p>ブログタイトル:<%=@blog.title%></p></div>
          <div class="panel-body">
          <p>ブログ内容:<%=@blog.content%></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <div class="row">
         <% unless @blog.user_id == current_user.id %>
           <%if @favorite.present? %>
             <%= link_to "お気に入りを解除する",favorite_path(blog_id:@blog.id),method: :delete, class: 'btn btn-danger btn-lg' %>
            <% else %>
             <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-success btn-lg' %>
            <% end %>
        <% end %>
        <%= link_to '戻る',blogs_path,class: 'btn btn-info btn-lg' %>
      </div>
      <p>コメント一覧</p>
      <div id="comments_area">
        <%= render partial: 'comments/index',locals:{ comments: @comments,blog: @blog } %>
     </div>
       <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
       <%= link_to '編集', edit_blog_path(@blog) %> |
     <%= link_to '戻る', blogs_path %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [blog, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <%= comment.content %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val("")

app/views/users/new.html.erb
<h1>新規登録</h1>

<%=form_with(model:@user,local:true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%=pluralize(@user.errors.count,"error")%>prohibited this @user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%=message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="form-group">
       <%=f.label :name %>
       <%=f.text_field :name, class: "form-control"%>
      </div>
      <div class="form-group">
       <%=f.label :email %>
       <%=f.email_field :email, class: "form-control"%>
      </div>
      <div class="form-group">
       <%=f.label :password %>
       <%=f.password_field :password, class: "form-control"%>
      </div>
      <div class="form-group">
       <%=f.label :password_confirmation %>
       <%=f.password_field :password_confirmation, class: "form-control"%>
      </div>
     <%=f.submit "送信"%>
    </div>
  </div>
</div>  
<% end %>

app/views/users/show.html.erb
<h1><%=@user.name %>のページ</h1>
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <div class="col-md-12 col-sm-6">
          <div class="panel-body"><p>email : <%=@user.email %></p></div>
     </div>
   </div>

  <h2>お気に入り一覧</h2>
      <div class="row">
        <table class="table table-responsive">
          <thead>
           <tr>
              <th>タイトル</th>
              <th>ブロガー名</th>
            </tr>
          </thead>
          <% @favorite_blogs.each_with_index do |fav,idx| %>
          <tbody>
            <tr>
              <td><%= idx + 1 %>.<%= fav.title %></td>
              <td><%= fav.user.name %></td>
            </tr>
          </tbody>
         <% end %>
        </table>
      </div>
  </div>
</div>

app/views/webpages/index.html.erb
<div class="container">
   <div class="row">
    <article>
      <div class="col-md-6">
        <h1><p class="text-primary">コンテンツA</p></h1>
              <ul class="row_A">
                  <li class="col-sm-6 col-md-3 bg-info">contents1</li>
                  <li class="col-sm-6 col-md-3 bg-info">contents2</li>
                  <li class="col-sm-6 col-md-3 bg-info">contents3</li>
                  <li class="col-sm-6 col-md-3 bg-info">contents4</li>
              </ul>
      <div class="btn-group" role="group">
	     <button type="button" class="btn btn-default">詳細表示</button>
      </div>
      </div>
    </article>
    <article>
      <div class="col-md-6">
        <h1><p class="text-primary">コンテンツB</p></h1>
              <ul class="row_B">
                  <li class="col-sm-6 col-md-3 bg-success">contents1</li>
                  <li class="col-sm-6 col-md-3 bg-success">contents2</li>
                  <li class="col-sm-6 col-md-3 bg-success">contents3</li>
                  <li class="col-sm-6 col-md-3 bg-success">contents4</li>
              </ul>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">詳細表示</button>
      </div>
      </div>
    </article>
  </div>
</div>