config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'webpages', to: 'webpages#index'
  resources :sessions, only: [:new,:create,:destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :blogs do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users,through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user

  def created_by?(input_user)
    return false unless input_user
    user_id == input_user.id
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_many :blogs

  validates :name,presence:true,length:{ maximum:40 }
  validates :email,presence:true,length:{ maximum:300 },
                  format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness:true

  before_save{ email.downcase! }
  has_secure_password
  validates :password,presence:true,length:{ minimum:6 }

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :set_blog,only:[:show,:edit,:update,:destroy]

  def index
    @blogs = Blog.all.all.order("blogs.created_at desc")
  end

  def new
    @blog = Blog.new
  end

  def show
    if logged_in?
      @favorite = current_user.favorites.find_by(blog_id: @blog.id)
      @comment = @blog.comments.build
      @comments = @blog.comments
    else
      redirect_to blogs_path, notice: "ログインしてください"
    end

  end

  def create
    if logged_in?
      @blog = Blog.new(blog_params)
      @blog.user_id = current_user.id
      if @blog.save
        # BlogCreateMailer.blog_create_mail(current_user).deliver
        redirect_to blogs_path, notice:"作成しました"
      end
    else
        @blog = Blog.new(blog_params)
        redirect_to blogs_path, notice:"ログインしてください"
    end
  end

  def edit
  end

  def update
  if @blog.update(blog_params)
    redirect_to blogs_path, notice:"編集しました"
  else
    @blog = Blog.new(blog_params)
    render 'edit'
  end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path notice:"削除しました"
  end

  private
  def blog_params
    params.require(:blog).permit(:name,:title,:content)
  end

  def set_blog
   @blog = Blog.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)

  respond_to do |format|
    if @comment.save
        format.js { render :index }
    else
        format.html { redirect_to blog_path(@blog), notice: '投稿できませんでした' }
    end
   end
  end

  private

  def comment_params
    params.require(:comment).permit(:blog_id,:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    logout
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
   if @user.save
    login(@user)
    redirect_to user_path(@user.id)
   else
    render 'new'
   end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
    @blog = current_user.favorites.find_by(blog_id:params[:blog_id])
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport",content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Blog</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'TOP',root_path%></li>
              <li><%= link_to 'ブログを作成する',new_blog_path %></li>
              <% if logged_in? %>
                <li><%= link_to 'ブログ一覧',blogs_path %></li>
                <li><%= link_to 'mypage',user_path(current_user.id) %></li>
                <li><%= link_to 'logout',session_path(current_user.id),method: :delete %></li>
              <% else %>
                <li><%= link_to 'sighup',new_user_path %></li>
                <li><%= link_to 'login',new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%flash.each do |key,value| %>
    <%= content_tag(:div,value,class:"#{key}") %>
    <% end %>

  <%= yield %>
    <footer class="footer">
        <div class="container">
          <p class="text-muted">5656blog</p>
        </div>
      </footer>
  </body>
</html>